# Generated by Django 5.0.4 on 2024-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_email_alter_account_role_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
